### PR TITLE
feat: add theme support for Spinner, Table and TableWithBrowserPagination components

### PR DESCRIPTION
**Pull request by wildergd**
fix: #1281

## Changes proposed in this PR:
- add theme support for Spinner component
- add theme support for Table component
- add theme support for TableWithBrowserPagination component

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/nexxtway/react-rainbow/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

@nexxtway/react-rainbow

### CODE REVIEW

**Comment by wildergd** [comment]
check header and rows styles in Table component because i added two new shadows and also used one existing with different color...

**Comment by TahimiLeonBravo** [comment]
@wildergd we need to customize the loading state
loading table

**Comment by TahimiLeonBravo** [comment]
@wildergd the default theme should look like the original design

**Comment by TahimiLeonBravo** [comment]
@wildergd review the header when Selectable rows are passed

checkmark header

**Comment by TahimiLeonBravo** [comment]
@wildergd review the styles when we have rows selected
selectable rows

**Pull request merged**
